openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
  description: API for creating users

paths:
  /api/users/companies/{companyId}/users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - Users
      parameters:
        - name: companyId
          in: path
          required: true
          description: ID of the company
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request or validation error
        '500':
          description: Internal server error

components:
  schemas:
    PhoneRequest:
      type: object
      properties:
        number:
          type: string
        citycode:
          type: string
        countrycode:
          type: string

    UserRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneRequest'

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        lastLogin:
          type: string
          format: date-time
        token:
          type: string
        isActive:
          type: boolean
